local order_list = {
	["j_dsix_basic_die"] = {order = 1},
	["j_dsix_chips_die"] = {order = 2},
	["j_dsix_chips_plus_die"] = {order = 3},
	["j_dsix_mult_die"] = {order = 4},
	["j_dsix_mult_plus_die"] = {order = 5},
	["j_dsix_xmult_die"] = {order = 6},
	["j_dsix_xmult_plus_die"] = {order = 7},
	["j_dsix_golden_die"] = {order = 8},
	["j_dsix_golden_plus_die"] = {order = 9},
	["j_dsix_golden_plus2_die"] = {order = 10},
	["j_dsix_tarot_die"] = {order = 11},
	["j_dsix_tarot_plus_die"] = {order = 12},
	["j_dsix_planet_die"] = {order = 13},
	["j_dsix_planet_plus_die"] = {order = 14},
	["j_dsix_spectral_die"] = {order = 15},
	["j_dsix_spectral_plus_die"] = {order = 16},
	["j_dsix_interstellar_die"] = {order = 17},
	["j_dsix_interstellar_plus_die"] = {order = 18},
	["j_dsix_chaos_die"] = {order = 19},
	["j_dsix_casino_die"] = {order = 20},
	["j_dsix_casino_plus_die"] = {order = 21},
	["j_dsix_self_selling_die"] = {order = 22},
	["j_dsix_party_die"] = {order = 23},
	["j_dsix_impure_gutless_die"] = {order = 24},
	["j_dsix_impure_broke_die"] = {order = 25},
	["j_dsix_impure_plague_die"] = {order = 26},
	["j_dsix_pure_savior_die"] = {order = 27},
	["j_dsix_pure_exchange_die"] = {order = 28},
	["j_dsix_pure_medical_die"] = {order = 29},
}

return order_list